package Secure;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shreya
 */
public class teacher extends javax.swing.JFrame {

    /**
     * Creates new form teacher
     */
    public teacher() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prn = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        atten = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("TEACHER");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel2.setText("STUDENT DATABASE");

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Structures", "Java", "Maths" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label5.setText("Choose subject-");

        label2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label2.setText("Enter the prn you want to search-");

        label3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label3.setText("Enter the updated attendance-");

        label4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label4.setText("Enter the updated marks-");

        jTable1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "prn", "first name", "last name", "Marks", "Attendance"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 689, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(334, 334, 334))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton1)
                                .addGap(102, 102, 102)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(atten, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(516, 516, 516)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(prn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(516, 516, 516)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(atten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2))))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 if(cb.getSelectedIndex()==0)
 {  try{
           Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
            int row = jTable1.getSelectedRow();
            String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
            String query = "SELECT DS.Prn,Firstname,Lastname,Marks,Attendance FROM DS,studentinfo WHERE DS.Prn=studentinfo.Prn AND DS.Prn ='"+tblclick+"'";
            
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next())
            {
         
                String m = String.valueOf(rs.getString("Marks"));
                marks.setText(m);
                String a= String.valueOf(rs.getString("Attendance"));
                atten.setText(a);
       }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 }
      else  if(cb.getSelectedIndex()==1)
 {  try{
           Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
            int row = jTable1.getSelectedRow();
            String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
            String query = "SELECT Java.Prn,Firstname,Lastname,Marks,Attendance FROM Java,studentinfo WHERE Java.Prn=studentinfo.Prn AND Java.Prn ='"+tblclick+"'";
            
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next())
            {
         
                String m = String.valueOf(rs.getString("Marks"));
                marks.setText(m);
                String a= String.valueOf(rs.getString("Attendance"));
                atten.setText(a);
       }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 }
 
 else if(cb.getSelectedIndex()==2)
 {  try{
           Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
            int row = jTable1.getSelectedRow();
            String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
            String query = "SELECT Maths.Prn,Firstname,Lastname,Marks,Attendance FROM Maths,studentinfo WHERE Maths.Prn=studentinfo.Prn AND Maths.Prn ='"+tblclick+"'";
            
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next())
            {
         
                String m = String.valueOf(rs.getString("Marks"));
                marks.setText(m);
                String a= String.valueOf(rs.getString("Attendance"));
                atten.setText(a);
       }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 }    
    }//GEN-LAST:event_jTable1MouseClicked

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        showTableData();
    }//GEN-LAST:event_cbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(cb.getSelectedIndex()==0)
       {
           try{
           int p=Integer.parseInt(prn.getText());
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = "SELECT DS.Prn,Firstname,Lastname,Marks,Attendance FROM DS,studentinfo WHERE DS.Prn=studentinfo.Prn AND DS.Prn = '"+p+"';";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
prn.setText("");
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
}
       }
 else if(cb.getSelectedIndex()==1)
       {
           try{
           int p=Integer.parseInt(prn.getText());
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = "SELECT Java.Prn,Firstname,Lastname,Marks,Attendance FROM Java,studentinfo WHERE Java.Prn=studentinfo.Prn AND Java.Prn = '"+p+"';";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
prn.setText("");
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
}
 }
   else if(cb.getSelectedIndex()==2)
       {
           try{
           int p=Integer.parseInt(prn.getText());
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = "SELECT Maths.Prn,Firstname,Lastname,Marks,Attendance FROM Maths,studentinfo WHERE Maths.Prn=studentinfo.Prn AND Maths.Prn = '"+p+"';";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
prn.setText("");
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex);
}
 }
    prn.setText("");
    atten.setText("");
    marks.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 int row = jTable1.getSelectedRow();
String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
int a=Integer.parseInt(atten.getText());
int m =Integer.parseInt(marks.getText());

if(cb.getSelectedIndex()==0)
{
try{
    Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
    
 String query = "UPDATE ds SET Marks='"+m+"',Attendance='"+a+"' WHERE Prn='"+tblclick+"';";
 
 stmt.executeUpdate(query);
 JOptionPane.showMessageDialog(null, "Updated Successfully");
 prn.setText("");
atten.setText("");
marks.setText("");
 showTableData(); 
 }
 catch(Exception ex){
 JOptionPane.showMessageDialog(null, ex);
 }       
}
else if(cb.getSelectedIndex()==1)
{
try{
    Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
    
 String query = "UPDATE Java SET Marks='"+m+"',Attendance='"+a+"' WHERE Prn='"+tblclick+"';";
 
 stmt.executeUpdate(query);
 JOptionPane.showMessageDialog(null, "Updated Successfully");
 prn.setText("");
atten.setText("");
marks.setText("");
 showTableData(); 
 }
 catch(Exception ex){
 JOptionPane.showMessageDialog(null, ex);
 }       
}
else if(cb.getSelectedIndex()==2)
{
try{
    Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
    Statement stmt = (Statement) con.createStatement();
    
 String query = "UPDATE Maths SET Marks='"+m+"',Attendance='"+a+"' WHERE Prn='"+tblclick+"';";
 
 stmt.executeUpdate(query);
 JOptionPane.showMessageDialog(null, "Updated Successfully");
 prn.setText("");
atten.setText("");
marks.setText("");
 showTableData(); 
 }
 catch(Exception ex){
 JOptionPane.showMessageDialog(null, ex);
 }       
}      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int input= JOptionPane.showConfirmDialog(null,"Are you sure you want to exit?");
       if(input==0)
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
 public void showTableData(){
     if(cb.getSelectedIndex()==0)
     {
try{
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = " SELECT DS.Prn,Firstname,Lastname,Marks,Attendance FROM DS,studentinfo WHERE DS.Prn=studentinfo.Prn;";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex); 
}
 }
    else if(cb.getSelectedIndex()==1)
    {try{
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = " SELECT Java.Prn,Firstname,Lastname,Marks,Attendance FROM Java,studentinfo WHERE Java.Prn=studentinfo.Prn;";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex); 
}
    }
     
    else if(cb.getSelectedIndex()==2)
    {
        try{
Connection con = (Connection)
    DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/kiwi","root","shreya");
Statement stmt = (Statement) con.createStatement();
String query = " SELECT Maths.Prn,Firstname,Lastname,Marks,Attendance FROM Maths,studentinfo WHERE Maths.Prn=studentinfo.Prn;";
 ResultSet rs = stmt.executeQuery(query);
jTable1.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex); 
}
    }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atten;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField prn;
    // End of variables declaration//GEN-END:variables
}
